project_id = "lcydidwtujaciqfagnyd"

[functions.recommend-content]
verify_jwt = false

[functions.generate-course]
verify_jwt = false

[functions.generate-presentation]
verify_jwt = false

[functions.project_ingest]
verify_jwt = false

[functions.project_plan]
verify_jwt = false

[functions.artifact_act]
verify_jwt = false

[functions.artifact_submit]
verify_jwt = false

[functions.project_checkin]
verify_jwt = false

[functions.bik-lookup]
verify_jwt = false